//audio managment
Crafty.audio.add({
	bgMusic: ["", // wav
		"media/ZombieBattleQN.mp3", //map3
		"media/ZombieBattleQN.ogg"], //ogg
	signCreate: ["",
		"media/InvocPoto.mp3",
		"media/InvocPoto.ogg"],
	signMove: ["",
		"media/TournagePoto.mp3",
		"media/TournagePoto.ogg"],
	signDelete: ["",
		"media/EnlevagePoto.mp3",
		"media/EnlevagePoto.ogg"],
	signBroken: ["",
		"media/SignBroken.mp3",
		"media/SignBroken.ogg"],
	doorOpen: ["",
		"media/DoorOpening.mp3",
		"media/DoorOpening.ogg"],
	doorClose: ["",
		"media/DoorClosing.mp3",
		"media/DoorClosing.ogg"],
	holeDig: ["",
		"media/DigHole.mp3",
		"media/DigHole.ogg"],
	zombieDie: ["",
		"media/ZombiDies1.mp3",
		"media/ZombiDies1.ogg"],
	zombieSounds: ["",
		"media/Zombi1.mp3",
		"media/Zombi1.ogg"],
	zombieRage: ["",
		"media/ZombiRage.mp3",
		"media/ZombiRage.ogg"],
	fortressAttack: ["",
		"media/ZombiAttackBase.mp3",
		"media/ZombiAttackBase.ogg"],
	soldierDie: ["",
		"media/SoldierDies.mp3",
		"media/SoldierDies.ogg"],
	cityDie: ["",
		"media/CityDies.mp3",
		"media/CityDies.ogg"],
	gameOver: ["",
		"media/GameOver.mp3",
		"media/GameOver.ogg"],
	pause: ["",
		"media/LaPause.mp3",
		"media/LaPause.ogg"]
});

// Use Crafty.audio.play(String id, number repeat); to play sounds repeat time (-1 => loop)
